### ISSUE TITLE
Continue button is not displayed when single file upload fails

### ISSUE THREAD

**Issue by LNT00** [andysh-uk/blue-twilight#68] opened 2017-10-03 12:28 UTC
Go to an album and upload a photo. If the upload fails, then there is no Continue button. It's only displayed on successfully upload.

![no_continue](https://user-images.githubusercontent.com/32333032/31124944-36dc15f6-a84f-11e7-8ae8-e20384f73657.jpg)

Please see failed file:
[clouds_sky_top_view_116717_6480x4320.zip](https://github.com/pandy06269/blue-twilight/files/1352219/clouds_sky_top_view_116717_6480x4320.zip)

Note: This file failed to upload on my gallery because it's larger than the max file size, it's working on the demo gallery.

**Comment by pandy06269** [comment] 2017-10-03 18:23
This is by design.

If the upload fails there is nothing to continue to. Perhaps I could just add a Close button in this case?

If you upload multiple files and one fails but others do succeed, you should have the option of continuing to analyse what did upload correctly. Is this working for you?

**Comment by LNT00** [comment] 2017-10-03 19:03
Yes, continue works correctly when at least one file is successfully added. The issue is only when adding a single file and that fails.  A Close button would fix this.

**Comment by andysh-uk** [comment] 2018-07-12 22:18
This has been resolved in 2.1.1

**Closed by andysh-uk** 2018-07-12 22:18 UTC
Labels: bug
